# Generated by Django 4.1.7 on 2023-03-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_learning', '0008_learningcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcourse',
            old_name='course_level',
            new_name='level',
        ),
    ]
