# Generated by Django 4.1.7 on 2023-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='integer',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='boolean_2',
            field=models.BooleanField(default=True),
        ),
    ]
