# Generated by Django 4.1.7 on 2023-03-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_remove_testmodel_integer_remove_testmodel_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='color',
            field=models.CharField(choices=[('red', 'red light'), ('blue', 'blue light'), ('yellow', 'yellow light')], default='n/a', max_length=20),
            preserve_default=False,
        ),
    ]
