# Generated by Django 4.1.7 on 2023-03-22 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_colorchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
